CREATE TABLE [dbo].[AdvanceRequest]
(
	[Id] BIGINT NOT NULL PRIMARY KEY IDENTITY,
	[EmployeeId] BIGINT NOT NULL REFERENCES TenantEmployee,
	[DayId] BIGINT NOT NULL REFERENCES dbo.[Day],
	[EntityId] BIGINT NOT NULL REFERENCES dbo.Entity,
	[EntityAgreementId] BIGINT NOT NULL REFERENCES dbo.EntityAgreement,

	[AdvanceRequestDate] DATE NOT NULL,
	[Amount] DECIMAL(19,2) NOT NULL,

	[ActivityId] BIGINT NOT NULL,
	[SqliteAdvanceRequestId] BIGINT NOT NULL DEFAULT 0,
	[DateCreated] DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
	[DateUpdated] DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),

	[RequestNotes] NVARCHAR(512),
	[Status] NVARCHAR(50) NOT NULL DEFAULT 'Pending',
	[AmountApproved] DECIMAL(19,2) NOT NULL DEFAULT 0,
	[ApproveNotes] NVARCHAR(512),
	[ReviewedBy] NVARCHAR(50),
	[ReviewDate] DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
	[CreatedBy] NVARCHAR(50),
	[UpdatedBy] NVARCHAR(50),
)
GO
