CREATE TABLE [dbo].[ItemMaster]
(
	[Id] BIGINT NOT NULL PRIMARY KEY Identity,
	[ItemCode] NVARCHAR(50) NOT NULL,
	[ItemDesc] NVARCHAR(100) NOT NULL,
	[Category] NVARCHAR(50) NOT NULL,
	[Unit]     NVARCHAR(10) NOT NULL,
	[Classification] NVARCHAR(10) NOT NULL DEFAULT '',
--	[TypeName] NVARCHAR(50) NOT NULL DEFAULT '',
--	[Rate] DECIMAL(19,2) NOT NULL DEFAULT 0,
	[IsActive] BIT NOT NULL DEFAULT 1
)
