CREATE UNIQUE NONCLUSTERED INDEX [IX_ProductPrice_ProductId_AreaCode] ON [dbo].[ProductPrice]
(
	[ProductId] ASC,
	[AreaCode] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO
