CREATE TABLE [dbo].[StockInputTag]
(
	[Id] BIGINT NOT NULL PRIMARY KEY Identity,
	[GRNNumber] NVARCHAR(20) NOT NULL,
	[ReceiveDate] DATETIME2 NOT NULL,

	[VendorName] NVARCHAR(50) NOT NULL,
	[VendorBillNo] NVARCHAR(20) NOT NULL,
	[VendorBillDate] DATETIME2 NOT NULL,

	[TotalItemCount] INT NOT NULL,
	[TotalAmount] DECIMAL(19,2) NOT NULL,
	[Notes] NVARCHAR(100) NOT NULL,
	[Status] NVARCHAR(50) NOT NULL DEFAULT 'Received',

	[ZoneCode] NVARCHAR(50) NOT NULL,
	[AreaCode] NVARCHAR(50) NOT NULL,
	[TerritoryCode] NVARCHAR(50) NOT NULL,
	[HQCode] NVARCHAR(50) NOT NULL,
	[StaffCode] NVARCHAR(10) NOT NULL DEFAULT '',
--	[WarehouseType] NVARCHAR(50) NOT NULL,

	[ReviewNotes] NVARCHAR(100),
	[ReviewedBy] NVARCHAR(50),
	[ReviewDate] DATETIME2 NOT NULL DEFAULT '2000-01-01',

	[CreatedBy] NVARCHAR(50) NOT NULL DEFAULT '',
	[UpdatedBy] NVARCHAR(50) NOT NULL DEFAULT '',
	[DateCreated] DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
	[DateUpdated] DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),

	[IsEditAllowed] BIT NOT NULL DEFAULT 1,
	[CyclicCount] BIGINT NOT NULL DEFAULT 1
)
