CREATE TABLE [dbo].[StockRequestTag]
(
	[Id] BIGINT NOT NULL PRIMARY KEY Identity,
	[RequestNumber] NVARCHAR(20) NOT NULL,
	[RequestDate] DATETIME2 NOT NULL,

	[Notes] NVARCHAR(100) NOT NULL,
	[Status] NVARCHAR(50) NOT NULL DEFAULT 'Received',

	[ZoneCode] NVARCHAR(50) NOT NULL,
	[AreaCode] NVARCHAR(50) NOT NULL,
	[TerritoryCode] NVARCHAR(50) NOT NULL,
	[HQCode] NVARCHAR(50) NOT NULL,
	[StaffCode] NVARCHAR(10) NOT NULL,

	[RequestType] NVARCHAR(50) NOT NULL DEFAULT 'StockIssueRequest',

	[CreatedBy] NVARCHAR(50) NOT NULL DEFAULT '',
	[UpdatedBy] NVARCHAR(50) NOT NULL DEFAULT '',
	[DateCreated] DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
	[DateUpdated] DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),

	[CyclicCount] BIGINT NOT NULL DEFAULT 1
)
