CREATE TABLE [dbo].[OfficeHierarchy]
(
	[Id] INT NOT NULL PRIMARY KEY Identity,
	[TenantId] BIGINT NOT NULL REFERENCES dbo.Tenant,
	[ZoneCode] NVARCHAR(10) NOT NULL,
	[AreaCode] NVARCHAR(10) NOT NULL,
	[TerritoryCode] NVARCHAR(10) NOT NULL,
	[HQCode] NVARCHAR(10) NOT NULL,
	[IsActive] BIT NOT NULL DEFAULT 1
)
