CREATE TABLE [dbo].[Document]
(
	[ID] INT NOT NULL PRIMARY KEY IDENTITY,
    [Type] NVARCHAR(50) NULL,
    [OtherType] NVARCHAR(50) NULL,
    [Path] NVARCHAR(200) NULL,
    [StartDate] DATETIME2 NULL,
    [EndDate] DATETIME2 NULL,
    [Status] BIT NOT NULL DEFAULT 1,
    [CreatedBy] NVARCHAR(100) NULL,
    [CreatedOn] DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    [ModifiedBy] NVARCHAR(100) NULL,
    [ModifiedOn] DATETIME2 NOT NULL DEFAULT GETUTCDATE()
)
