CREATE TABLE [dbo].[EntitySurvey]
(
	[Id] BIGINT NOT NULL PRIMARY KEY IDENTITY,
	[EntityId] BIGINT NOT NULL REFERENCES [Entity]([Id]), 
	[WorkflowSeasonId]  BIGINT NOT NULL REFERENCES [WorkFlowSeason]([Id]), 
	[SurveyNumber] NVARCHAR(50) NOT NULL,

	[MajorCrop] NVARCHAR(50) NOT NULL,
	[LastCrop] NVARCHAR(50) NOT NULL,
	[WaterSource] NVARCHAR(50) NOT NULL,
	[SoilType] NVARCHAR(50) NOT NULL,
	[SowingDate] DATETIME2 NOT NULL,
	[LandSizeInAcres] DECIMAL(19,2) NOT NULL DEFAULT 0,

	[Status] NVARCHAR(50) NOT NULL DEFAULT 'Pending',

	[ActivityId] BIGINT NOT NULL DEFAULT 0,

	[DateCreated] DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
	[DateUpdated] DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
	[CreatedBy] NVARCHAR(50) NOT NULL,
	[UpdatedBy] NVARCHAR(50) NOT NULL
)
