CREATE TABLE [dbo].[EntityBankDetail]
(
	[Id] BIGINT NOT NULL PRIMARY KEY IDENTITY,
	[EntityId] BIGINT NOT NULL REFERENCES [Entity]([Id]), 

	--[IsPrimaryAccount] BIT NOT NULL,
	[IsSelfAccount] BIT NOT NULL,
	[AccountHolderName] NVARCHAR(50) NOT NULL,
	[AccountHolderPAN] NVARCHAR(50) NOT NULL,
	[BankName] NVARCHAR(50) NOT NULL,
	[BankAccount] NVARCHAR(50) NOT NULL,
	[BankIFSC] NVARCHAR(50) NOT NULL,
	[BankBranch] NVARCHAR(50) NOT NULL,
	[ImageCount] INT NOT NULL DEFAULT 0,

	[Status] NVARCHAR(50) NOT NULL DEFAULT 'Pending',
	[IsApproved] BIT NOT NULL DEFAULT 0,
	[Comments] NVARCHAR(100) NOT NULL DEFAULT '',

	[SqliteBankDetailId] BIGINT NOT NULL,
	[DateCreated] DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
	[DateUpdated] DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
	[CreatedBy] NVARCHAR(50) NOT NULL,
	[UpdatedBy] NVARCHAR(50) NOT NULL,
	IsActive BIT NOT NULL DEFAULT 1
)
