CREATE TABLE [dbo].[DWS]
(
	[Id] BIGINT NOT NULL PRIMARY KEY Identity,
	[STRTagId] BIGINT NOT NULL References dbo.[STRTag],
	[STRId] BIGINT NOT NULL References dbo.[STR],

	[DWSNumber] NVARCHAR(50) NOT NULL,
	[DWSDate] DATETIME2 NOT NULL,

	[BagCount] BIGINT NOT NULL,
	[FilledBagsWeightKg] DECIMAL(19,2) NOT NULL,
	[EmptyBagsWeightKg] DECIMAL(19,2) NOT NULL,

	[SiloDeductPercent] DECIMAL(19,2) NOT NULL DEFAULT 0,
	[GoodsWeight] DECIMAL(19,2) NOT NULL DEFAULT 0,
	[SiloDeductWt] DECIMAL(19,2) NOT NULL DEFAULT 0,

	[SiloDeductWtOverride] DECIMAL(19,2) NOT NULL DEFAULT 0,
	[NetPayableWt] DECIMAL(19,2) NOT NULL DEFAULT 0,

	[RatePerKg] DECIMAL(19,2) NOT NULL DEFAULT 0,
	[GoodsPrice] DECIMAL(19,2) NOT NULL DEFAULT 0,
	[DeductAmount] DECIMAL(19,2) NOT NULL DEFAULT 0,

	[NetPayable] DECIMAL(19,2) NOT NULL DEFAULT 0,

	[EntityId] BIGINT NOT NULL REFERENCES dbo.Entity,
	--[EntityName] NVARCHAR(50) NOT NULL,
	--[HQCode] NVARCHAR(10) NOT NULL DEFAULT '',

	[AgreementId] BIGINT NOT NULL REFERENCES dbo.EntityAgreement,
	[Agreement] NVARCHAR(50) NOT NULL,
	[EntityWorkFlowDetailId] BIGINT NOT NULL,
	[TypeName] NVARCHAR(50) NOT NULL,
	[TagName] NVARCHAR(50) NOT NULL,

	[OrigBagCount] BIGINT NOT NULL DEFAULT 0,
	[OrigFilledBagsKg] DECIMAL(19,2) NOT NULL DEFAULT 0,
	[OrigEmptyBagsKg] DECIMAL(19,2) NOT NULL DEFAULT 0,
	
	[Status] NVARCHAR(50) NOT NULL DEFAULT 'Pending',
	[Comments] NVARCHAR(500) NOT NULL DEFAULT '',

	[WtApprovedBy] NVARCHAR(50) NULL,
	[WtApprovedDate] DATETIME2 NULL,
	[AmountApprovedBy] NVARCHAR(50) NULL,
	[AmountApprovedDate] DATETIME2 NULL,
	[PaidBy] NVARCHAR(50) NULL,
	[PaidDate] DATETIME2 NULL,
	[PaymentReference] NVARCHAR(50) NULL,

	[BankAccountName] NVARCHAR(50) NULL,
	[BankName] NVARCHAR(50) NULL,
	[BankAccount] NVARCHAR(50) NULL,
	[BankIFSC] NVARCHAR(50) NULL,
	[BankBranch] NVARCHAR(50) NULL,


	[ActivityId] BIGINT NOT NULL DEFAULT 0,

	[CyclicCount] BIGINT NOT NULL DEFAULT 1,

	[CreatedBy] NVARCHAR(50) NOT NULL DEFAULT '',
	[UpdatedBy] NVARCHAR(50) NOT NULL DEFAULT '',
	[DateCreated] DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
	[DateUpdated] DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),

	[SqliteSTRDWSId] BIGINT NOT NULL DEFAULT 0,
)
