CREATE TABLE [dbo].[STRWeight]
(
	[Id] BIGINT NOT NULL PRIMARY KEY Identity,
	[STRNumber] NVARCHAR(50) NOT NULL,
	[STRDate] DATETIME2 NOT NULL,

	[EntryWeight] DECIMAL(19,2) NOT NULL,
	[ExitWeight] DECIMAL(19,2) NOT NULL,
	[SiloNumber] NVARCHAR(50) NOT NULL,
	[SiloIncharge] NVARCHAR(50) NOT NULL,
	[UnloadingIncharge] NVARCHAR(50) NOT NULL,
	[ExitOdometer] BIGINT NOT NULL,
	[BagCount] BIGINT NOT NULL,
	[DeductionPercent] DECIMAL(19,2) NOT NULL DEFAULT 0,
	[Notes] NVARCHAR(1000) NOT NULL DEFAULT '',
	[Status] NVARCHAR(50) NOT NULL DEFAULT 'Pending',

	[VehicleNumber] NVARCHAR(50) NOT NULL DEFAULT '',
	[DWSCount] BIGINT NOT NULL DEFAULT 0,

	[CreatedBy] NVARCHAR(50) NOT NULL DEFAULT '',
	[UpdatedBy] NVARCHAR(50) NOT NULL DEFAULT '',
	[DateCreated] DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
	[DateUpdated] DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),

	[IsEditAllowed] BIT NOT NULL DEFAULT 1,
	[CyclicCount] BIGINT NOT NULL DEFAULT 1
)
