CREATE TABLE [dbo].[EmployeeDay]
(
	[Id] BIGINT NOT NULL PRIMARY KEY Identity,
	[TenantEmployeeId] BIGINT NOT NULL REFERENCES dbo.TenantEmployee,  
	[DayId] BIGINT NOT NULL REFERENCES dbo.[Day],

	[StartTime] [DATETIME2] NOT NULL DEFAULT SYSUTCDATETIME(),
	[EndTime] [DATETIME2],
	[TotalDistanceInMeters] DECIMAL(19,5) NOT NULL Default 0,
	[TotalOrderAmount] DECIMAL(19,2) NOT NULL DEFAULT 0,
	[TotalPaymentAmount] DECIMAL(19,2) NOT NULL DEFAULT 0,
	[TotalReturnAmount] DECIMAL(19,2) NOT NULL DEFAULT 0,
	[TotalExpenseAmount] DECIMAL(19,2) NOT NULL DEFAULT 0,

	[TotalActivityCount] INT NOT NULL DEFAULT 0,

	[CurrentLatitude] DECIMAL(19,9) NOT NULL DEFAULT 0,
	[CurrentLongitude] DECIMAL(19,9) NOT NULL DEFAULT 0,

	[CurrentLocTime] DATETIME2 NOT NULL DEFAULT '2000-01-01',

	[HasMultipleStarts] BIT NOT NULL DEFAULT 0,
	[HQCode] NVARCHAR(10) NOT NULL DEFAULT '',
	[AreaCode] NVARCHAR(10) NOT NULL DEFAULT '',
	[PhoneModel] NVARCHAR(100),
	[PhoneOS] NVARCHAR(10),
	[AppVersion] NVARCHAR(10)
)
