CREATE TABLE [dbo].[IMEI]
(
	[Id] INT NOT NULL PRIMARY KEY Identity,
	[IMEINumber] NVARCHAR(50) NOT NULL,
	[TenantEmployeeId] BIGINT NOT NULL REFERENCES dbo.TenantEmployee,
	[DateCreated] DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
	[DateUpdated] DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
	[IsActive] BIT NOT NULL DEFAULT 1
)
