CREATE TABLE [dbo].[PurgeLog]
(
	[Id] BIGINT NOT NULL PRIMARY KEY Identity,
	[DateFrom] DATETIME NOT NULL,
	[DateTo] DATETIME NOT NULL,
	[ActionPurged] BIGINT NOT NULL DEFAULT 0,
	[ActionDupPurged] BIGINT NOT NULL DEFAULT 0,
	[ExpensePurged] BIGINT NOT NULL DEFAULT 0,
	[OrderPurged] BIGINT NOT NULL DEFAULT 0,
	[PaymentPurged] BIGINT NOT NULL DEFAULT 0,
	[EntityPurged] BIGINT NOT NULL DEFAULT 0,
	[ReturnPurged] BIGINT NOT NULL DEFAULT 0,
	[DateCreated] DATETIME2 NOT NULL DEFAULT SysUtcDateTime()
)
