// <auto-generated />
using System;
using Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Persistence.Migrations
{
    [DbContext(typeof(AccountingDbContext))]
    [Migration("20220313104529_InitialCreation")]
    partial class InitialCreation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.15")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Domain.Uploads.BankStatements", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("AccountNo")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BankName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("Branch_Code")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("Credit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Debit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefNo_ChequeNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Transaction_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Transaction_Literal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Transaction_Mnemonic")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Value_Date")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("BankStatements");
                });
#pragma warning restore 612, 618
        }
    }
}
