CREATE TABLE [dbo].[EntityWorkFlow]
(
	[Id] BIGINT NOT NULL PRIMARY KEY IDENTITY,
	[EmployeeId] BIGINT NOT NULL REFERENCES TenantEmployee(Id),
	[EmployeeCode] NVARCHAR(10) NOT NULL,
	--[HQCode] NVARCHAR(10) NULL,
	[EntityId] BIGINT NOT NULL REFERENCES dbo.Entity,
	--[EntityName] NVARCHAR(50) NOT NULL,

	[AgreementId] BIGINT NOT NULL REFERENCES dbo.EntityAgreement,
	[Agreement] NVARCHAR(50) NOT NULL DEFAULT '',

	[TypeName] NVARCHAR(50) NOT NULL DEFAULT '',
	[TagName] NVARCHAR(50) NOT NULL,
	[InitiationDate] DATE NOT NULL,
	[IsComplete] BIT NOT NULL DEFAULT 0,

	[DateCreated] DATETIME2 NOT NULL DEFAULT SysutcDATETIME(),
	[Timestamp]  DATETIME2 NOT NULL DEFAULT SysutcDATETIME(),
)
