CREATE TABLE [dbo].[Expense]
(
	[Id] BIGINT NOT NULL PRIMARY KEY Identity,
	[EmployeeId] BIGINT NOT NULL REFERENCES TenantEmployee,
	[DayId] BIGINT NOT NULL REFERENCES dbo.[Day],
	[TotalAmount] DECIMAL(19,2) NOT NULL DEFAULT 0,

	---- approval fields
	--[IsApproved] BIT NOT NULL DEFAULT 0,
	--[ApproveDate] DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
	--[ApproveRef] NVARCHAR(255),
	--[ApproveNotes] NVARCHAR(2048),
	--[ApproveAmount] DECIMAL(19,2) NOT NULL DEFAULT 0,
	--[ApprovedBy] NVARCHAR(50) NOT NULL DEFAULT '',

	[IsZoneApproved] BIT NOT NULL DEFAULT 0,
	[IsAreaApproved] BIT NOT NULL DEFAULT 0,
	[IsTerritoryApproved] BIT NOT NULL DEFAULT 0,

	[DateCreated] DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
	[Timestamp] DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
)
