//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Activity()
        {
            this.ActivityImages = new HashSet<ActivityImage>();
            this.ActivityContacts = new HashSet<ActivityContact>();
            this.SqliteEntityWorkFlows = new HashSet<SqliteEntityWorkFlow>();
        }
    
        public long Id { get; set; }
        public long EmployeeDayId { get; set; }
        public string ClientName { get; set; }
        public string ClientType { get; set; }
        public string ActivityType { get; set; }
        public string Comments { get; set; }
        public System.DateTime At { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateUpdated { get; set; }
        public string ClientPhone { get; set; }
        public int ImageCount { get; set; }
        public string ClientCode { get; set; }
        public bool AtBusiness { get; set; }
        public decimal ActivityAmount { get; set; }
        public int ContactCount { get; set; }
        public int ActivityTrackingType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActivityImage> ActivityImages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActivityContact> ActivityContacts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SqliteEntityWorkFlow> SqliteEntityWorkFlows { get; set; }
        public virtual EmployeeDay EmployeeDay { get; set; }
    }
}
