//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdvanceRequest
    {
        public long Id { get; set; }
        public long EmployeeId { get; set; }
        public long DayId { get; set; }
        public long EntityId { get; set; }
        public long EntityAgreementId { get; set; }
        public System.DateTime AdvanceRequestDate { get; set; }
        public decimal Amount { get; set; }
        public long ActivityId { get; set; }
        public long SqliteAdvanceRequestId { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateUpdated { get; set; }
        public string RequestNotes { get; set; }
        public string Status { get; set; }
        public decimal AmountApproved { get; set; }
        public string ApproveNotes { get; set; }
        public string ReviewedBy { get; set; }
        public System.DateTime ReviewDate { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual Day Day { get; set; }
        public virtual TenantEmployee TenantEmployee { get; set; }
        public virtual EntityAgreement EntityAgreement { get; set; }
        public virtual Entity Entity { get; set; }
    }
}
