//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnswerDetail
    {
        public long Id { get; set; }
        public long AnswerId { get; set; }
        public long QuestionPaperQuestionId { get; set; }
        public long QuestionPaperAnswerId { get; set; }
    
        public virtual Answer Answer { get; set; }
    }
}
