//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BonusAgreementDetail
    {
        public long Id { get; set; }
        public long AgreementId { get; set; }
        public string AgreementNumber { get; set; }
        public System.DateTime AgreementDate { get; set; }
        public long EntityId { get; set; }
        public string EntityName { get; set; }
        public string TypeName { get; set; }
        public string SeasonName { get; set; }
        public decimal LandSizeInAcres { get; set; }
        public decimal RatePerKg { get; set; }
        public decimal NetWeight { get; set; }
        public decimal NetPaid { get; set; }
        public decimal BonusRate { get; set; }
        public decimal BonusAmountPayable { get; set; }
        public decimal BonusAmountPaid { get; set; }
        public string BonusStatus { get; set; }
        public string HQCode { get; set; }
        public string PaymentReference { get; set; }
        public string BankAccountName { get; set; }
        public string BankName { get; set; }
        public string BankAccountNumber { get; set; }
        public string BankIFSC { get; set; }
        public string BankBranch { get; set; }
        public string Comments { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateUpdated { get; set; }
    
        public virtual EntityAgreement EntityAgreement { get; set; }
        public virtual Entity Entity { get; set; }
    }
}
