//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BonusRate
    {
        public long Id { get; set; }
        public string SeasonName { get; set; }
        public string TypeName { get; set; }
        public decimal WeightTonsFrom { get; set; }
        public decimal WeightTonsTo { get; set; }
        public decimal RatePaise { get; set; }
    }
}
