//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CodeTable
    {
        public int Id { get; set; }
        public string CodeType { get; set; }
        public string CodeValue { get; set; }
        public int DisplaySequence { get; set; }
        public bool IsActive { get; set; }
        public string CodeName { get; set; }
        public long TenantId { get; set; }
    
        public virtual Tenant Tenant { get; set; }
    }
}
