//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerDivisionBalance
    {
        public long ID { get; set; }
        public string CustomerCode { get; set; }
        public string DivisionCode { get; set; }
        public string SegmentCode { get; set; }
        public decimal CreditLimit { get; set; }
        public decimal Outstanding { get; set; }
        public decimal LongOutstanding { get; set; }
        public decimal Target { get; set; }
        public decimal Sales { get; set; }
        public decimal Payment { get; set; }
        public System.DateTime DATE { get; set; }
    }
}
