//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DayPlanTarget
    {
        public long Id { get; set; }
        public long TenantId { get; set; }
        public long EmployeeId { get; set; }
        public long DayId { get; set; }
        public string EmployeeCode { get; set; }
        public System.DateTime PlanDate { get; set; }
        public decimal TargetSales { get; set; }
        public decimal TargetCollection { get; set; }
        public decimal TargetVigoreSales { get; set; }
        public int TargetDealerAppointment { get; set; }
        public long SqliteDayPlanTargetId { get; set; }
        public int TargetDemoActivity { get; set; }
    
        public virtual Day Day { get; set; }
        public virtual TenantEmployee TenantEmployee { get; set; }
        public virtual Tenant Tenant { get; set; }
    }
}
