//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DW
    {
        public long Id { get; set; }
        public long STRTagId { get; set; }
        public long STRId { get; set; }
        public string DWSNumber { get; set; }
        public System.DateTime DWSDate { get; set; }
        public long BagCount { get; set; }
        public decimal FilledBagsWeightKg { get; set; }
        public decimal EmptyBagsWeightKg { get; set; }
        public decimal SiloDeductPercent { get; set; }
        public decimal GoodsWeight { get; set; }
        public decimal SiloDeductWt { get; set; }
        public decimal SiloDeductWtOverride { get; set; }
        public decimal NetPayableWt { get; set; }
        public decimal RatePerKg { get; set; }
        public decimal GoodsPrice { get; set; }
        public decimal DeductAmount { get; set; }
        public decimal NetPayable { get; set; }
        public long EntityId { get; set; }
        public long AgreementId { get; set; }
        public string Agreement { get; set; }
        public long EntityWorkFlowDetailId { get; set; }
        public string TypeName { get; set; }
        public string TagName { get; set; }
        public long OrigBagCount { get; set; }
        public decimal OrigFilledBagsKg { get; set; }
        public decimal OrigEmptyBagsKg { get; set; }
        public string Status { get; set; }
        public string Comments { get; set; }
        public string PaidBy { get; set; }
        public Nullable<System.DateTime> PaidDate { get; set; }
        public string PaymentReference { get; set; }
        public long ActivityId { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateUpdated { get; set; }
        public long SqliteSTRDWSId { get; set; }
        public long CyclicCount { get; set; }
        public string WtApprovedBy { get; set; }
        public Nullable<System.DateTime> WtApprovedDate { get; set; }
        public string AmountApprovedBy { get; set; }
        public Nullable<System.DateTime> AmountApprovedDate { get; set; }
        public string BankAccountName { get; set; }
        public string BankName { get; set; }
        public string BankAccount { get; set; }
        public string BankIFSC { get; set; }
        public string BankBranch { get; set; }
    
        public virtual EntityAgreement EntityAgreement { get; set; }
        public virtual STR STR { get; set; }
        public virtual STRTag STRTag { get; set; }
        public virtual Entity Entity { get; set; }
    }
}
