//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DWSAudit
    {
        public long Id { get; set; }
        public long STRTagId { get; set; }
        public long STRId { get; set; }
        public long DWSId { get; set; }
        public string DWSNumber { get; set; }
        public System.DateTime DWSDate { get; set; }
        public long BagCount { get; set; }
        public decimal FilledBagsWeightKg { get; set; }
        public decimal EmptyBagsWeightKg { get; set; }
        public long EntityId { get; set; }
        public long AgreementId { get; set; }
        public string Agreement { get; set; }
        public long EntityWorkFlowDetailId { get; set; }
        public string TypeName { get; set; }
        public string TagName { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime DateCreated { get; set; }
    }
}
