//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeDay
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EmployeeDay()
        {
            this.Activities = new HashSet<Activity>();
            this.Trackings = new HashSet<Tracking>();
        }
    
        public long Id { get; set; }
        public long TenantEmployeeId { get; set; }
        public long DayId { get; set; }
        public System.DateTime StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public decimal TotalDistanceInMeters { get; set; }
        public decimal TotalOrderAmount { get; set; }
        public decimal TotalPaymentAmount { get; set; }
        public decimal TotalReturnAmount { get; set; }
        public decimal TotalExpenseAmount { get; set; }
        public decimal CurrentLatitude { get; set; }
        public decimal CurrentLongitude { get; set; }
        public bool HasMultipleStarts { get; set; }
        public string HQCode { get; set; }
        public string AreaCode { get; set; }
        public string PhoneModel { get; set; }
        public string PhoneOS { get; set; }
        public string AppVersion { get; set; }
        public int TotalActivityCount { get; set; }
        public System.DateTime CurrentLocTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Activity> Activities { get; set; }
        public virtual Day Day { get; set; }
        public virtual TenantEmployee TenantEmployee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tracking> Trackings { get; set; }
    }
}
