//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntityWorkFlow
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EntityWorkFlow()
        {
            this.EntityWorkFlowDetails = new HashSet<EntityWorkFlowDetail>();
        }
    
        public long Id { get; set; }
        public long EmployeeId { get; set; }
        public string EmployeeCode { get; set; }
        public long EntityId { get; set; }
        public System.DateTime InitiationDate { get; set; }
        public bool IsComplete { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime Timestamp { get; set; }
        public long AgreementId { get; set; }
        public string Agreement { get; set; }
        public string TypeName { get; set; }
        public string TagName { get; set; }
    
        public virtual EntityAgreement EntityAgreement { get; set; }
        public virtual TenantEmployee TenantEmployee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EntityWorkFlowDetail> EntityWorkFlowDetails { get; set; }
        public virtual Entity Entity { get; set; }
    }
}
