//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntityAgreement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EntityAgreement()
        {
            this.AdvanceRequests = new HashSet<AdvanceRequest>();
            this.TerminateAgreementRequests = new HashSet<TerminateAgreementRequest>();
            this.IssueReturns = new HashSet<IssueReturn>();
            this.EntityWorkFlows = new HashSet<EntityWorkFlow>();
            this.DWS = new HashSet<DW>();
            this.BonusAgreementDetails = new HashSet<BonusAgreementDetail>();
        }
    
        public long Id { get; set; }
        public long EntityId { get; set; }
        public long WorkflowSeasonId { get; set; }
        public string AgreementNumber { get; set; }
        public string Status { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateUpdated { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public bool IsPassbookReceived { get; set; }
        public System.DateTime PassbookReceivedDate { get; set; }
        public decimal LandSizeInAcres { get; set; }
        public decimal RatePerKg { get; set; }
        public long ActivityId { get; set; }
        public bool BonusProcessed { get; set; }
        public string ZoneCode { get; set; }
        public string ZoneName { get; set; }
        public string AreaCode { get; set; }
        public string AreaName { get; set; }
        public string TerritoryCode { get; set; }
        public string TerritoryName { get; set; }
        public string HQCode { get; set; }
        public string HQName { get; set; }
        public Nullable<long> EmployeeId { get; set; }
    
        public virtual WorkflowSeason WorkflowSeason { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdvanceRequest> AdvanceRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TerminateAgreementRequest> TerminateAgreementRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IssueReturn> IssueReturns { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EntityWorkFlow> EntityWorkFlows { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DW> DWS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BonusAgreementDetail> BonusAgreementDetails { get; set; }
        public virtual Entity Entity { get; set; }
    }
}
