//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExcelUploadError
    {
        public long Id { get; set; }
        public long ExcelUploadStatusId { get; set; }
        public string MessageType { get; set; }
        public string CellReference { get; set; }
        public string ExpectedValue { get; set; }
        public string ActualValue { get; set; }
        public string Description { get; set; }
    
        public virtual ExcelUploadStatu ExcelUploadStatu { get; set; }
    }
}
