//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExcelUploadStatu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ExcelUploadStatu()
        {
            this.ExcelUploadErrors = new HashSet<ExcelUploadError>();
        }
    
        public long Id { get; set; }
        public long TenantId { get; set; }
        public string UploadType { get; set; }
        public string UploadFileName { get; set; }
        public long RecordCount { get; set; }
        public string RequestedBy { get; set; }
        public bool IsCompleteRefresh { get; set; }
        public System.DateTime RequestTimestamp { get; set; }
        public System.DateTime PostingTimestamp { get; set; }
        public bool IsPosted { get; set; }
        public string UploadTable { get; set; }
        public string LocalFileName { get; set; }
        public bool IsParsed { get; set; }
        public int ErrorCount { get; set; }
        public bool IsLocked { get; set; }
        public System.DateTime LockTimestamp { get; set; }
    
        public virtual Tenant Tenant { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExcelUploadError> ExcelUploadErrors { get; set; }
    }
}
