//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExcelUploadHistory
    {
        public long Id { get; set; }
        public long TenantId { get; set; }
        public string UploadType { get; set; }
        public string UploadFileName { get; set; }
        public long RecordCount { get; set; }
        public string RequestedBy { get; set; }
        public bool IsCompleteRefresh { get; set; }
        public System.DateTime RequestTimestamp { get; set; }
        public System.DateTime PostingTimestamp { get; set; }
    
        public virtual Tenant Tenant { get; set; }
    }
}
