//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpenseItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ExpenseItem()
        {
            this.ExpenseItemImages = new HashSet<ExpenseItemImage>();
        }
    
        public long Id { get; set; }
        public long ExpenseId { get; set; }
        public int SequenceNumber { get; set; }
        public string ExpenseType { get; set; }
        public string TransportType { get; set; }
        public decimal Amount { get; set; }
        public long OdometerStart { get; set; }
        public long OdometerEnd { get; set; }
        public int ImageCount { get; set; }
        public string FuelType { get; set; }
        public decimal FuelQuantityInLiters { get; set; }
        public string Comment { get; set; }
        public decimal DeductedAmount { get; set; }
        public decimal RevisedAmount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExpenseItemImage> ExpenseItemImages { get; set; }
        public virtual Expense Expense { get; set; }
    }
}
