//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpenseApproval
    {
        public long Id { get; set; }
        public long ExpenseId { get; set; }
        public string ApproveLevel { get; set; }
        public System.DateTime ApproveDate { get; set; }
        public string ApproveRef { get; set; }
        public string ApproveNotes { get; set; }
        public decimal ApproveAmount { get; set; }
        public string ApprovedBy { get; set; }
        public System.DateTime Timestamp { get; set; }
    
        public virtual Expense Expense { get; set; }
    }
}
