//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expense
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Expense()
        {
            this.ExpenseApprovals = new HashSet<ExpenseApproval>();
            this.ExpenseItems = new HashSet<ExpenseItem>();
        }
    
        public long Id { get; set; }
        public long EmployeeId { get; set; }
        public long DayId { get; set; }
        public decimal TotalAmount { get; set; }
        public bool IsZoneApproved { get; set; }
        public bool IsAreaApproved { get; set; }
        public bool IsTerritoryApproved { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime Timestamp { get; set; }
    
        public virtual Day Day { get; set; }
        public virtual TenantEmployee TenantEmployee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExpenseApproval> ExpenseApprovals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExpenseItem> ExpenseItems { get; set; }
    }
}
