//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRNNumber
    {
        public long Id { get; set; }
        public long Sequence { get; set; }
        public string GRNNumber1 { get; set; }
        public bool IsUsed { get; set; }
        public System.DateTime UsedTimestamp { get; set; }
    }
}
