//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMEI
    {
        public int Id { get; set; }
        public long TenantEmployeeId { get; set; }
        public bool IsActive { get; set; }
        public string IMEINumber { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateUpdated { get; set; }
    
        public virtual TenantEmployee TenantEmployee { get; set; }
    }
}
