//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class IssueReturn
    {
        public long Id { get; set; }
        public long EmployeeId { get; set; }
        public long DayId { get; set; }
        public long EntityId { get; set; }
        public Nullable<long> EntityAgreementId { get; set; }
        public long ItemMasterId { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public string TransactionType { get; set; }
        public int Quantity { get; set; }
        public string SlipNumber { get; set; }
        public decimal LandSizeInAcres { get; set; }
        public decimal ItemRate { get; set; }
        public string AppliedTransactionType { get; set; }
        public long AppliedItemMasterId { get; set; }
        public int AppliedQuantity { get; set; }
        public decimal AppliedItemRate { get; set; }
        public string Status { get; set; }
        public long ActivityId { get; set; }
        public long SqliteIssueReturnId { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateUpdated { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public string Comments { get; set; }
        public long CyclicCount { get; set; }
    
        public virtual Day Day { get; set; }
        public virtual EntityAgreement EntityAgreement { get; set; }
        public virtual TenantEmployee TenantEmployee { get; set; }
        public virtual ItemMaster ItemMaster { get; set; }
        public virtual ItemMaster ItemMaster1 { get; set; }
        public virtual Entity Entity { get; set; }
    }
}
