//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemMasterTypeName
    {
        public long Id { get; set; }
        public long ItemMasterId { get; set; }
        public string TypeName { get; set; }
        public decimal Rate { get; set; }
        public decimal ReturnRate { get; set; }
    
        public virtual ItemMaster ItemMaster { get; set; }
    }
}
