//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfficeHierarchy
    {
        public int Id { get; set; }
        public string ZoneCode { get; set; }
        public string AreaCode { get; set; }
        public string TerritoryCode { get; set; }
        public string HQCode { get; set; }
        public bool IsActive { get; set; }
        public long TenantId { get; set; }
    
        public virtual Tenant Tenant { get; set; }
    }
}
