//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderItem
    {
        public long Id { get; set; }
        public long OrderId { get; set; }
        public int SerialNumber { get; set; }
        public string ProductCode { get; set; }
        public int UnitQuantity { get; set; }
        public decimal UnitPrice { get; set; }
        public decimal Amount { get; set; }
        public int RevisedUnitQuantity { get; set; }
        public decimal RevisedAmount { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
        public string UpdatedBy { get; set; }
        public decimal DiscountPercent { get; set; }
        public decimal DiscountedPrice { get; set; }
        public decimal ItemPrice { get; set; }
        public decimal GstPercent { get; set; }
        public decimal GstAmount { get; set; }
        public decimal NetPrice { get; set; }
        public decimal RevisedDiscountPercent { get; set; }
        public decimal RevisedDiscountedPrice { get; set; }
        public decimal RevisedItemPrice { get; set; }
        public decimal RevisedGstPercent { get; set; }
        public decimal RevisedGstAmount { get; set; }
        public decimal RevisedNetPrice { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
