//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.OrderItems = new HashSet<OrderItem>();
            this.OrderImages = new HashSet<OrderImage>();
        }
    
        public long Id { get; set; }
        public long EmployeeId { get; set; }
        public long DayId { get; set; }
        public string CustomerCode { get; set; }
        public string OrderType { get; set; }
        public System.DateTime OrderDate { get; set; }
        public decimal TotalAmount { get; set; }
        public long ItemCount { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateUpdated { get; set; }
        public long SqliteOrderId { get; set; }
        public bool IsApproved { get; set; }
        public System.DateTime ApproveDate { get; set; }
        public string ApproveRef { get; set; }
        public string ApproveNotes { get; set; }
        public decimal ApproveAmount { get; set; }
        public string ApprovedBy { get; set; }
        public decimal RevisedTotalAmount { get; set; }
        public Nullable<System.DateTime> LockTimestamp { get; set; }
        public bool IsCustomerSMSSent { get; set; }
        public bool IsAgentSMSSent { get; set; }
        public int ImageCount { get; set; }
        public decimal TotalGST { get; set; }
        public decimal NetAmount { get; set; }
        public string DiscountType { get; set; }
        public decimal DiscountPercentage { get; set; }
        public decimal RevisedDiscountPercentage { get; set; }
        public decimal RevisedTotalGST { get; set; }
        public decimal RevisedNetAmount { get; set; }
        public bool IsExported { get; set; }
        public Nullable<System.DateTime> ExportedDate { get; set; }
    
        public virtual Day Day { get; set; }
        public virtual TenantEmployee TenantEmployee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderItem> OrderItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderImage> OrderImages { get; set; }
    }
}
