//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PPA
    {
        public long Id { get; set; }
        public long TenantId { get; set; }
        public string AreaCode { get; set; }
        public string StaffCode { get; set; }
        public string PPACode { get; set; }
        public string PPAName { get; set; }
        public string PPAContact { get; set; }
        public string Location { get; set; }
    
        public virtual Tenant Tenant { get; set; }
    }
}
