//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductPrice
    {
        public int Id { get; set; }
        public int ProductId { get; set; }
        public string AreaCode { get; set; }
        public long Stock { get; set; }
        public decimal MRP { get; set; }
        public decimal DISTPrice { get; set; }
        public decimal PDISTPrice { get; set; }
        public decimal DEALERPrice { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
