//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurgeLog
    {
        public long Id { get; set; }
        public System.DateTime DateFrom { get; set; }
        public System.DateTime DateTo { get; set; }
        public long ActionPurged { get; set; }
        public long ActionDupPurged { get; set; }
        public long ExpensePurged { get; set; }
        public long OrderPurged { get; set; }
        public long PaymentPurged { get; set; }
        public long ReturnPurged { get; set; }
        public System.DateTime DateCreated { get; set; }
        public long EntityPurged { get; set; }
    }
}
