//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionPaperQuestion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QuestionPaperQuestion()
        {
            this.QuestionPaperAnswers = new HashSet<QuestionPaperAnswer>();
        }
    
        public long Id { get; set; }
        public long QuestionPaperId { get; set; }
        public string CategoryName { get; set; }
        public string SubCategoryName { get; set; }
        public string QuestionTypeName { get; set; }
        public string QText { get; set; }
        public bool AdditionalComment { get; set; }
        public int DisplaySequence { get; set; }
        public string CategoryDesc { get; set; }
        public string SubCategoryDesc { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateUpdated { get; set; }
    
        public virtual QuestionPaper QuestionPaper { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuestionPaperAnswer> QuestionPaperAnswers { get; set; }
    }
}
