//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionPaperAnswer
    {
        public long Id { get; set; }
        public long QuestionPaperQuestionId { get; set; }
        public string AText { get; set; }
    
        public virtual QuestionPaperQuestion QuestionPaperQuestion { get; set; }
    }
}
