//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReturnOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ReturnOrder()
        {
            this.ReturnOrderItems = new HashSet<ReturnOrderItem>();
        }
    
        public long Id { get; set; }
        public long EmployeeId { get; set; }
        public long DayId { get; set; }
        public string CustomerCode { get; set; }
        public System.DateTime ReturnOrderDate { get; set; }
        public decimal TotalAmount { get; set; }
        public long ItemCount { get; set; }
        public string ReferenceNumber { get; set; }
        public string Comment { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateUpdated { get; set; }
        public long SqliteReturnOrderId { get; set; }
        public bool IsApproved { get; set; }
        public System.DateTime ApproveDate { get; set; }
        public string ApproveRef { get; set; }
        public string ApproveNotes { get; set; }
        public decimal ApproveAmount { get; set; }
        public string ApprovedBy { get; set; }
    
        public virtual Day Day { get; set; }
        public virtual TenantEmployee TenantEmployee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReturnOrderItem> ReturnOrderItems { get; set; }
    }
}
