//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesPerson
    {
        public int Id { get; set; }
        public string StaffCode { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public string HQCode { get; set; }
        public string Grade { get; set; }
        public string Department { get; set; }
        public string Designation { get; set; }
        public string OwnershipType { get; set; }
        public string VehicleType { get; set; }
        public string FuelType { get; set; }
        public string VehicleNumber { get; set; }
        public bool IsActive { get; set; }
        public string BusinessRole { get; set; }
        public bool OverridePrivateVehicleRatePerKM { get; set; }
        public decimal TwoWheelerRatePerKM { get; set; }
        public decimal FourWheelerRatePerKM { get; set; }
    }
}
