//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModel
{
    using System;
    
    public partial class sp_DashboardData_ResultSet
    {
        public System.DateTime Date { get; set; }
        public long TenantEmployeeId { get; set; }
        public long EmployeeDayId { get; set; }
        public int ActivityCount { get; set; }
        public decimal TotalDistanceInMetersAtMilestones { get; set; }
        public decimal TotalDistanceInMetersAfterLastMilestone { get; set; }
    }
}
