//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SqliteTaskAction
    {
        public long Id { get; set; }
        public long BatchId { get; set; }
        public long EmployeeId { get; set; }
        public bool IsNewTask { get; set; }
        public long TaskId { get; set; }
        public string ParentReferenceTaskId { get; set; }
        public long TaskAssignmentId { get; set; }
        public string SqliteActionPhoneDbId { get; set; }
        public string Status { get; set; }
        public System.DateTime NotificationDate { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public string PhoneDbId { get; set; }
        public long TaskActionId { get; set; }
        public bool IsProcessed { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateUpdated { get; set; }
    
        public virtual SqliteActionBatch SqliteActionBatch { get; set; }
    }
}
