//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SqliteAction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SqliteAction()
        {
            this.SqliteActionImages = new HashSet<SqliteActionImage>();
            this.SqliteActionContacts = new HashSet<SqliteActionContact>();
            this.SqliteActionLocations = new HashSet<SqliteActionLocation>();
        }
    
        public long Id { get; set; }
        public long SqliteTableId { get; set; }
        public long BatchId { get; set; }
        public long EmployeeId { get; set; }
        public System.DateTime At { get; set; }
        public string Name { get; set; }
        public int ActivityTrackingType { get; set; }
        public decimal Latitude { get; set; }
        public decimal Longitude { get; set; }
        public long MNC { get; set; }
        public long MCC { get; set; }
        public long LAC { get; set; }
        public long CellId { get; set; }
        public string ClientName { get; set; }
        public string ClientPhone { get; set; }
        public string ClientType { get; set; }
        public string ActivityType { get; set; }
        public string Comments { get; set; }
        public bool IsProcessed { get; set; }
        public bool IsPostedSuccessfully { get; set; }
        public long TrackingId { get; set; }
        public long ActivityId { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateUpdated { get; set; }
        public int ImageCount { get; set; }
        public string PhoneModel { get; set; }
        public string PhoneOS { get; set; }
        public string AppVersion { get; set; }
        public string PhoneDbId { get; set; }
        public string ClientCode { get; set; }
        public string IMEI { get; set; }
        public int ContactCount { get; set; }
        public bool AtBusiness { get; set; }
        public string InstrumentId { get; set; }
        public decimal ActivityAmount { get; set; }
        public string LocationTaskStatus { get; set; }
        public string LocationException { get; set; }
        public int LocationCount { get; set; }
        public decimal DerivedLatitude { get; set; }
        public decimal DerivedLongitude { get; set; }
        public string DerivedLocSource { get; set; }
    
        public virtual SqliteActionBatch SqliteActionBatch { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SqliteActionImage> SqliteActionImages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SqliteActionContact> SqliteActionContacts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SqliteActionLocation> SqliteActionLocations { get; set; }
    }
}
