//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SqliteTask
    {
        public long Id { get; set; }
        public long BatchId { get; set; }
        public long EmployeeId { get; set; }
        public bool IsNewEntity { get; set; }
        public string ParentReferenceId { get; set; }
        public string ProjectName { get; set; }
        public string Description { get; set; }
        public string ActivityType { get; set; }
        public string ClientType { get; set; }
        public string ClientName { get; set; }
        public string ClientCode { get; set; }
        public System.DateTime PlannedStartDate { get; set; }
        public System.DateTime PlannedEndDate { get; set; }
        public string Comments { get; set; }
        public string Status { get; set; }
        public System.DateTime NotificationDate { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public string PhoneDbId { get; set; }
        public long TaskId { get; set; }
        public long TaskAssignmentId { get; set; }
        public bool IsProcessed { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateUpdated { get; set; }
        public long ProjectId { get; set; }
    
        public virtual SqliteActionBatch SqliteActionBatch { get; set; }
    }
}
