//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SqliteSurvey
    {
        public long Id { get; set; }
        public long BatchId { get; set; }
        public long EmployeeId { get; set; }
        public bool IsNewEntity { get; set; }
        public long EntityId { get; set; }
        public string EntityName { get; set; }
        public string SeasonName { get; set; }
        public string SowingType { get; set; }
        public decimal Acreage { get; set; }
        public System.DateTime SowingDate { get; set; }
        public string MajorCrop { get; set; }
        public string LastCrop { get; set; }
        public string WaterSource { get; set; }
        public string SoilType { get; set; }
        public string PhoneDbId { get; set; }
        public string ParentReferenceId { get; set; }
        public bool IsProcessed { get; set; }
        public long EntitySurveyId { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateUpdated { get; set; }
        public string ActivityId { get; set; }
        public System.DateTime SurveyDate { get; set; }
    
        public virtual SqliteActionBatch SqliteActionBatch { get; set; }
    }
}
