//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SqliteDayPlanTarget
    {
        public long Id { get; set; }
        public long BatchId { get; set; }
        public long EmployeeId { get; set; }
        public System.DateTime PlanDate { get; set; }
        public decimal TargetSales { get; set; }
        public decimal TargetCollection { get; set; }
        public decimal TargetVigoreSales { get; set; }
        public int TargetDealerAppointment { get; set; }
        public string PhoneDbId { get; set; }
        public bool IsProcessed { get; set; }
        public long DayPlanTargetId { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateUpdated { get; set; }
        public int TargetDemoActivity { get; set; }
    
        public virtual SqliteActionBatch SqliteActionBatch { get; set; }
    }
}
