//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SqliteAnswer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SqliteAnswer()
        {
            this.SqliteAnswerDetails = new HashSet<SqliteAnswerDetail>();
        }
    
        public long Id { get; set; }
        public long CrossRefId { get; set; }
        public long QuestionPaperQuestionId { get; set; }
        public bool HasTextComment { get; set; }
        public string TextComment { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SqliteAnswerDetail> SqliteAnswerDetails { get; set; }
        public virtual SqliteQuestionnaire SqliteQuestionnaire { get; set; }
    }
}
