//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SqliteActionLocation
    {
        public long Id { get; set; }
        public long SqliteActionId { get; set; }
        public string Source { get; set; }
        public decimal Latitude { get; set; }
        public decimal Longitude { get; set; }
        public string LocationTaskStatus { get; set; }
        public string LocationException { get; set; }
        public bool IsGood { get; set; }
        public System.DateTime UtcAt { get; set; }
    
        public virtual SqliteAction SqliteAction { get; set; }
    }
}
