//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SqliteSTR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SqliteSTR()
        {
            this.SqliteSTRImages = new HashSet<SqliteSTRImage>();
            this.SqliteSTRDWS = new HashSet<SqliteSTRDW>();
        }
    
        public long Id { get; set; }
        public long BatchId { get; set; }
        public long EmployeeId { get; set; }
        public string STRNumber { get; set; }
        public string VehicleNumber { get; set; }
        public string DriverName { get; set; }
        public string DriverPhone { get; set; }
        public long DWSCount { get; set; }
        public long BagCount { get; set; }
        public decimal GrossWeight { get; set; }
        public decimal NetWeight { get; set; }
        public long StartOdometer { get; set; }
        public long EndOdometer { get; set; }
        public System.DateTime STRDate { get; set; }
        public bool IsNew { get; set; }
        public bool IsTransferred { get; set; }
        public string TransfereeName { get; set; }
        public string TransfereePhone { get; set; }
        public int ImageCount { get; set; }
        public string ActivityId { get; set; }
        public string ActivityId2 { get; set; }
        public string PhoneDbId { get; set; }
        public bool IsProcessed { get; set; }
        public long STRId { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateUpdated { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public System.DateTime TimeStamp2 { get; set; }
    
        public virtual SqliteActionBatch SqliteActionBatch { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SqliteSTRImage> SqliteSTRImages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SqliteSTRDW> SqliteSTRDWS { get; set; }
    }
}
