//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SqliteAgreement
    {
        public long Id { get; set; }
        public long BatchId { get; set; }
        public long EmployeeId { get; set; }
        public bool IsNewEntity { get; set; }
        public long EntityId { get; set; }
        public string EntityName { get; set; }
        public string SeasonName { get; set; }
        public string TypeName { get; set; }
        public decimal Acreage { get; set; }
        public System.DateTime AgreementDate { get; set; }
        public string ActivityId { get; set; }
        public string ParentReferenceId { get; set; }
        public bool IsProcessed { get; set; }
        public long EntityAgreementId { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateUpdated { get; set; }
        public string PhoneDbId { get; set; }
        public string TerritoryCode { get; set; }
        public string TerritoryName { get; set; }
        public string HQCode { get; set; }
        public string HQName { get; set; }
    
        public virtual SqliteActionBatch SqliteActionBatch { get; set; }
    }
}
