//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SqliteOrderItem
    {
        public long Id { get; set; }
        public long SqliteOrderId { get; set; }
        public int SerialNumber { get; set; }
        public string ProductCode { get; set; }
        public int UnitQuantity { get; set; }
        public decimal UnitPrice { get; set; }
        public decimal Amount { get; set; }
        public decimal DiscountPercent { get; set; }
        public decimal DiscountedPrice { get; set; }
        public decimal ItemPrice { get; set; }
        public decimal GstPercent { get; set; }
        public decimal GstAmount { get; set; }
        public decimal NetPrice { get; set; }
    
        public virtual SqliteOrder SqliteOrder { get; set; }
    }
}
