//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SqliteExpense
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SqliteExpense()
        {
            this.SqliteExpenseImages = new HashSet<SqliteExpenseImage>();
        }
    
        public long Id { get; set; }
        public long SqliteTableId { get; set; }
        public long BatchId { get; set; }
        public long EmployeeId { get; set; }
        public int SequenceNumber { get; set; }
        public string ExpenseType { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<long> OdometerStart { get; set; }
        public Nullable<long> OdometerEnd { get; set; }
        public string VehicleType { get; set; }
        public int ImageCount { get; set; }
        public bool IsProcessed { get; set; }
        public long ExpenseItemId { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateUpdated { get; set; }
        public string FuelType { get; set; }
        public decimal FuelQuantityInLiters { get; set; }
        public string Comment { get; set; }
    
        public virtual SqliteActionBatch SqliteActionBatch { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SqliteExpenseImage> SqliteExpenseImages { get; set; }
    }
}
