//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SqliteAdvanceRequest
    {
        public long Id { get; set; }
        public long BatchId { get; set; }
        public long EmployeeId { get; set; }
        public bool IsNewEntity { get; set; }
        public bool IsNewAgreement { get; set; }
        public long EntityId { get; set; }
        public string EntityName { get; set; }
        public long AgreementId { get; set; }
        public string Agreement { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime AdvanceRequestDate { get; set; }
        public string ActivityId { get; set; }
        public string ParentReferenceId { get; set; }
        public bool IsProcessed { get; set; }
        public long AdvanceRequestId { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateUpdated { get; set; }
        public string Notes { get; set; }
    
        public virtual SqliteActionBatch SqliteActionBatch { get; set; }
    }
}
