//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SqliteEntityWorkFlowV2
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SqliteEntityWorkFlowV2()
        {
            this.SqliteEntityWorkFlowFollowUps = new HashSet<SqliteEntityWorkFlowFollowUp>();
            this.SqliteEntityWorkFlowItemUseds = new HashSet<SqliteEntityWorkFlowItemUsed>();
        }
    
        public long Id { get; set; }
        public long EntityId { get; set; }
        public string EntityType { get; set; }
        public string EntityName { get; set; }
        public long AgreementId { get; set; }
        public string Agreement { get; set; }
        public string Phase { get; set; }
        public bool IsStarted { get; set; }
        public System.DateTime Date { get; set; }
        public string MaterialType { get; set; }
        public int MaterialQuantity { get; set; }
        public bool GapFillingRequired { get; set; }
        public int GapFillingSeedQuantity { get; set; }
        public int LaborCount { get; set; }
        public int PercentCompleted { get; set; }
        public bool IsProcessed { get; set; }
        public long EntityWorkFlowId { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime Timestamp { get; set; }
        public long BatchId { get; set; }
        public long EmployeeId { get; set; }
        public System.DateTime FieldVisitDate { get; set; }
        public string ActivityId { get; set; }
        public string TypeName { get; set; }
        public string TagName { get; set; }
        public long EntityWorkFlowDetailId { get; set; }
        public long FollowUpCount { get; set; }
        public string BatchNumber { get; set; }
        public string LandSize { get; set; }
        public string DWSEntry { get; set; }
        public long ItemCount { get; set; }
        public long ItemsUsedCount { get; set; }
        public long YieldExpected { get; set; }
        public long BagsIssued { get; set; }
        public System.DateTime HarvestDate { get; set; }
    
        public virtual SqliteActionBatch SqliteActionBatch { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SqliteEntityWorkFlowFollowUp> SqliteEntityWorkFlowFollowUps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SqliteEntityWorkFlowItemUsed> SqliteEntityWorkFlowItemUseds { get; set; }
    }
}
