//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SqliteEntityWorkFlowItemUsed
    {
        public long Id { get; set; }
        public long SqliteEntityWorkFlowId { get; set; }
        public string ItemName { get; set; }
    
        public virtual SqliteEntityWorkFlowV2 SqliteEntityWorkFlowV2 { get; set; }
    }
}
