//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SqlitePayment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SqlitePayment()
        {
            this.SqlitePaymentImages = new HashSet<SqlitePaymentImage>();
        }
    
        public long Id { get; set; }
        public long BatchId { get; set; }
        public long EmployeeId { get; set; }
        public string CustomerCode { get; set; }
        public string PaymentType { get; set; }
        public System.DateTime PaymentDate { get; set; }
        public decimal TotalAmount { get; set; }
        public string Comment { get; set; }
        public int ImageCount { get; set; }
        public bool IsProcessed { get; set; }
        public long PaymentId { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateUpdated { get; set; }
        public string PhoneDbId { get; set; }
        public string PhoneActivityId { get; set; }
    
        public virtual SqliteActionBatch SqliteActionBatch { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SqlitePaymentImage> SqlitePaymentImages { get; set; }
    }
}
