//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffDailyReportData
    {
        public long Id { get; set; }
        public long TenantId { get; set; }
        public string StaffCode { get; set; }
        public string DivisionCode { get; set; }
        public string SegmentCode { get; set; }
        public decimal TargetOutstandingYTD { get; set; }
        public decimal TotalCostYTD { get; set; }
        public decimal CGAYTD { get; set; }
        public decimal GT180YTD { get; set; }
        public decimal CollectionTargetYTD { get; set; }
        public decimal CollectionActualYTD { get; set; }
        public decimal SalesTargetYTD { get; set; }
        public decimal SalesActualYTD { get; set; }
        public System.DateTime DATE { get; set; }
        public string AreaCode { get; set; }
    
        public virtual Tenant Tenant { get; set; }
    }
}
