//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffDivisionInput
    {
        public string Staff_Code { get; set; }
        public string Staff_Name { get; set; }
        public string Division_Code { get; set; }
        public string Division_Name { get; set; }
    }
}
