//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockRequestFulfill
    {
        public long Id { get; set; }
        public long StockRequestId { get; set; }
        public long StockRequestTagId { get; set; }
        public long ItemMasterId { get; set; }
        public long StockInputId { get; set; }
        public long StockBalanceId { get; set; }
        public long StockBalanceCyclicCount { get; set; }
        public int QuantityInHand { get; set; }
        public int QuantityIssued { get; set; }
        public long CyclicCount { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateUpdated { get; set; }
    
        public virtual StockBalance StockBalance { get; set; }
        public virtual StockInput StockInput { get; set; }
        public virtual StockRequest StockRequest { get; set; }
        public virtual StockRequestTag StockRequestTag { get; set; }
        public virtual ItemMaster ItemMaster { get; set; }
    }
}
