//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockBalance
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StockBalance()
        {
            this.StockRequestFulfills = new HashSet<StockRequestFulfill>();
        }
    
        public long Id { get; set; }
        public long ItemMasterId { get; set; }
        public long StockQuantity { get; set; }
        public string ZoneCode { get; set; }
        public string AreaCode { get; set; }
        public string TerritoryCode { get; set; }
        public string HQCode { get; set; }
        public string StaffCode { get; set; }
        public long CyclicCount { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateUpdated { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockRequestFulfill> StockRequestFulfills { get; set; }
        public virtual ItemMaster ItemMaster { get; set; }
    }
}
