//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class STR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public STR()
        {
            this.STRImages = new HashSet<STRImage>();
            this.DWS = new HashSet<DW>();
        }
    
        public long Id { get; set; }
        public long STRTagId { get; set; }
        public long EmployeeId { get; set; }
        public string VehicleNumber { get; set; }
        public string DriverName { get; set; }
        public string DriverPhone { get; set; }
        public long DWSCount { get; set; }
        public long BagCount { get; set; }
        public decimal GrossWeight { get; set; }
        public decimal NetWeight { get; set; }
        public long StartOdometer { get; set; }
        public long EndOdometer { get; set; }
        public bool IsNew { get; set; }
        public bool IsTransferred { get; set; }
        public string TransfereeName { get; set; }
        public string TransfereePhone { get; set; }
        public int ImageCount { get; set; }
        public long ActivityId { get; set; }
        public long ActivityId2 { get; set; }
        public long BatchId { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateUpdated { get; set; }
        public long SqliteSTRId { get; set; }
        public string Status { get; set; }
    
        public virtual STRTag STRTag { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STRImage> STRImages { get; set; }
        public virtual TenantEmployee TenantEmployee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DW> DWS { get; set; }
    }
}
