//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class STRPayment
    {
        public long Id { get; set; }
        public Nullable<long> STRTagId { get; set; }
        public string STRNumber { get; set; }
        public string PaymentReference { get; set; }
        public Nullable<long> ShedToFirstLoadingOdo { get; set; }
        public Nullable<long> StartOdometer { get; set; }
        public Nullable<long> EndOdometer { get; set; }
        public Nullable<int> SiloToReturnKm { get; set; }
        public Nullable<int> TotalRunningKms { get; set; }
        public decimal CostPerKm { get; set; }
        public Nullable<decimal> TransportationCharges { get; set; }
        public int VehicleCapacityKgs { get; set; }
        public Nullable<decimal> GrossWeight { get; set; }
        public Nullable<decimal> SiloWeight { get; set; }
        public Nullable<decimal> ExtraTonnage { get; set; }
        public decimal ExtraCostPerTon { get; set; }
        public Nullable<decimal> ExtraTonCharges { get; set; }
        public Nullable<decimal> TollCharges { get; set; }
        public Nullable<decimal> WeighmentCharges { get; set; }
        public long BagCount { get; set; }
        public decimal HamaliRatePerBag { get; set; }
        public Nullable<decimal> HamaliCharges { get; set; }
        public Nullable<decimal> Others { get; set; }
        public Nullable<decimal> NetPayableAmount { get; set; }
        public string BankAccountName { get; set; }
        public string BankName { get; set; }
        public string BankAccount { get; set; }
        public string BankIFSC { get; set; }
        public string BankBranch { get; set; }
        public string Comments { get; set; }
        public string Status { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateUpdated { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual STRTag STRTag { get; set; }
    }
}
