//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskAction
    {
        public int Id { get; set; }
        public long XRefTaskId { get; set; }
        public long XRefActivityId { get; set; }
        public long XRefTaskAssignmentId { get; set; }
        public long EmployeeId { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public long SqliteTaskActionId { get; set; }
        public string Status { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateUpdated { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual Task Task { get; set; }
        public virtual TenantEmployee TenantEmployee { get; set; }
    }
}
