//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tenant
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tenant()
        {
            this.TenantEmployees = new HashSet<TenantEmployee>();
            this.TenantHolidays = new HashSet<TenantHoliday>();
            this.TenantWorkDays = new HashSet<TenantWorkDay>();
            this.TenantSMSSchedules = new HashSet<TenantSMSSchedule>();
            this.TenantSMSLogs = new HashSet<TenantSMSLog>();
            this.TenantSmsTypes = new HashSet<TenantSmsType>();
            this.CodeTables = new HashSet<CodeTable>();
            this.OfficeHierarchies = new HashSet<OfficeHierarchy>();
            this.ExcelUploadHistories = new HashSet<ExcelUploadHistory>();
            this.ExcelUploadStatus = new HashSet<ExcelUploadStatu>();
            this.Divisions = new HashSet<Division>();
            this.StaffDailyReportDatas = new HashSet<StaffDailyReportData>();
            this.TenantSmsDatas = new HashSet<TenantSmsData>();
            this.PPAs = new HashSet<PPA>();
            this.DayPlanTargets = new HashSet<DayPlanTarget>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public long TimeIntervalInMillisecondsForTracking { get; set; }
        public bool IsActive { get; set; }
        public decimal RatePerDistanceUnit { get; set; }
        public bool IsProcessingMobileData { get; set; }
        public bool IsTransformingDataFeed { get; set; }
        public Nullable<System.DateTime> MobileDataProcessingAt { get; set; }
        public bool IsSMSEnabled { get; set; }
        public bool IsSendingSMS { get; set; }
        public Nullable<System.DateTime> SMSProcessingAt { get; set; }
        public decimal MaxDiscountPercentage { get; set; }
        public string DiscountType { get; set; }
        public bool IsUploadingImage { get; set; }
        public Nullable<System.DateTime> UploadingImageAt { get; set; }
        public bool IsParsingUploadFile { get; set; }
        public Nullable<System.DateTime> TransformingDataFeedAt { get; set; }
        public Nullable<System.DateTime> ParsingUploadAt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TenantEmployee> TenantEmployees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TenantHoliday> TenantHolidays { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TenantWorkDay> TenantWorkDays { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TenantSMSSchedule> TenantSMSSchedules { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TenantSMSLog> TenantSMSLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TenantSmsType> TenantSmsTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CodeTable> CodeTables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OfficeHierarchy> OfficeHierarchies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExcelUploadHistory> ExcelUploadHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExcelUploadStatu> ExcelUploadStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Division> Divisions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StaffDailyReportData> StaffDailyReportDatas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TenantSmsData> TenantSmsDatas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PPA> PPAs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DayPlanTarget> DayPlanTargets { get; set; }
    }
}
