//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TenantEmployee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TenantEmployee()
        {
            this.TenantEmployee1 = new HashSet<TenantEmployee>();
            this.IMEIs = new HashSet<IMEI>();
            this.Orders = new HashSet<Order>();
            this.Payments = new HashSet<Payment>();
            this.ReturnOrders = new HashSet<ReturnOrder>();
            this.Expenses = new HashSet<Expense>();
            this.EmployeeDays = new HashSet<EmployeeDay>();
            this.AdvanceRequests = new HashSet<AdvanceRequest>();
            this.TerminateAgreementRequests = new HashSet<TerminateAgreementRequest>();
            this.STRs = new HashSet<STR>();
            this.IssueReturns = new HashSet<IssueReturn>();
            this.EntityWorkFlows = new HashSet<EntityWorkFlow>();
            this.ProjectAssignments = new HashSet<ProjectAssignment>();
            this.TaskActions = new HashSet<TaskAction>();
            this.TaskAssignments = new HashSet<TaskAssignment>();
            this.Entities = new HashSet<Entity>();
            this.GeoLocations = new HashSet<GeoLocation>();
            this.DayPlanTargets = new HashSet<DayPlanTarget>();
        }
    
        public long Id { get; set; }
        public long TenantId { get; set; }
        public Nullable<long> ManagerId { get; set; }
        public string Name { get; set; }
        public bool IsActive { get; set; }
        public string EmployeeCode { get; set; }
        public long TimeIntervalInMillisecondsForTracking { get; set; }
        public System.DateTime DateUpdated { get; set; }
        public System.DateTime DateCreated { get; set; }
        public bool SendLogFromPhone { get; set; }
        public bool ExecAppAccess { get; set; }
        public bool AutoUploadFromPhone { get; set; }
        public string ActivityPageName { get; set; }
        public string LocationFromType { get; set; }
        public bool EnhancedDebugEnabled { get; set; }
        public bool TestFeatureEnabled { get; set; }
        public bool VoiceFeatureEnabled { get; set; }
        public int ExecAppDetailLevel { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TenantEmployee> TenantEmployee1 { get; set; }
        public virtual TenantEmployee TenantEmployee2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IMEI> IMEIs { get; set; }
        public virtual Tenant Tenant { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReturnOrder> ReturnOrders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Expense> Expenses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeDay> EmployeeDays { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdvanceRequest> AdvanceRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TerminateAgreementRequest> TerminateAgreementRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STR> STRs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IssueReturn> IssueReturns { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EntityWorkFlow> EntityWorkFlows { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectAssignment> ProjectAssignments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskAction> TaskActions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskAssignment> TaskAssignments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Entity> Entities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GeoLocation> GeoLocations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DayPlanTarget> DayPlanTargets { get; set; }
    }
}
