//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TenantSMSLog
    {
        public int Id { get; set; }
        public long TenantId { get; set; }
        public string SmsType { get; set; }
        public System.DateTime SMSDateTime { get; set; }
        public string SMSText { get; set; }
        public string SMSApiResponse { get; set; }
        public string SenderName { get; set; }
    
        public virtual Tenant Tenant { get; set; }
    }
}
