//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TenantSmsData
    {
        public long Id { get; set; }
        public long TenantId { get; set; }
        public string TemplateName { get; set; }
        public string DataType { get; set; }
        public string MessageData { get; set; }
        public bool IsSent { get; set; }
        public bool IsFailed { get; set; }
        public string FailedText { get; set; }
        public Nullable<System.DateTime> LockTimestamp { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime Timestamp { get; set; }
    
        public virtual Tenant Tenant { get; set; }
    }
}
