//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tracking
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tracking()
        {
            this.Tracking1 = new HashSet<Tracking>();
            this.DistanceCalcErrorLogs = new HashSet<DistanceCalcErrorLog>();
        }
    
        public long Id { get; set; }
        public Nullable<long> ChainedTrackingId { get; set; }
        public long EmployeeDayId { get; set; }
        public System.DateTime At { get; set; }
        public decimal BeginGPSLatitude { get; set; }
        public decimal BeginGPSLongitude { get; set; }
        public decimal EndGPSLatitude { get; set; }
        public decimal EndGPSLongitude { get; set; }
        public string BeginLocationName { get; set; }
        public string EndLocationName { get; set; }
        public decimal BingMapsDistanceInMeters { get; set; }
        public decimal GoogleMapsDistanceInMeters { get; set; }
        public decimal LinearDistanceInMeters { get; set; }
        public bool DistanceCalculated { get; set; }
        public Nullable<System.DateTime> LockTimestamp { get; set; }
        public long ActivityId { get; set; }
        public bool IsMilestone { get; set; }
        public bool IsStartOfDay { get; set; }
        public bool IsEndOfDay { get; set; }
        public string ActivityType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tracking> Tracking1 { get; set; }
        public virtual Tracking Tracking2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DistanceCalcErrorLog> DistanceCalcErrorLogs { get; set; }
        public virtual EmployeeDay EmployeeDay { get; set; }
    }
}
