//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transporter
    {
        public long Id { get; set; }
        public string CompanyName { get; set; }
        public string VehicleType { get; set; }
        public string VehicleNo { get; set; }
        public string TransportationType { get; set; }
        public int SiloToReturnKM { get; set; }
        public int VehicleCapacityKgs { get; set; }
        public decimal HamaliRatePerBag { get; set; }
        public decimal CostPerKm { get; set; }
        public decimal ExtraCostPerTon { get; set; }
        public string CompanyCode { get; set; }
    }
}
