INSERT INTO CommonMaster VALUES    ('TransactionType', 'Bill', 'Bill', 10, 1),
                                 ('TransactionType', 'TDS', 'TDS', 20, 1),
                                 ('TransactionType', 'GSTTDS', 'GSTTDS', 30, 1),
                                 ('TransactionType', 'BillRoyalty', 'BillRoyalty', 40, 1),
								 ('TransactionType','BillPenalty','BilPenalty',50,1),
                                 ('TransactionType', 'BillCBF', 'BillCBF', 60, 1),
                                 ('TransactionType', 'BillLabourWelfareCess', 'BillLabourWelfareCess', 70, 1),
                                 ('TransactionType', 'BillOthers1', 'BillOthers1', 80, 1),
                                 ('TransactionType', 'BillOthers2', 'BillOthers2', 90, 1),
                                 ('TransactionType', 'BillOthers3', 'BillOthers3', 100, 1),
								  ('TransactionType', 'CESS', 'CESS', 110, 1);
