CREATE TABLE [dbo].[SqliteTask]
(
	[Id] BIGINT NOT NULL PRIMARY KEY IDENTITY(1,1),
	[BatchId] BIGINT NOT NULL REFERENCES  [SqliteActionBatch]([Id]),
	[EmployeeId] BIGINT NOT NULL,

	[IsNewEntity] BIT NOT NULL DEFAULT 0,
	[ParentReferenceId]  NVARCHAR(50) NOT NULL DEFAULT '',
	[ProjectName] NVARCHAR(50) NOT NULL DEFAULT 'Default',
	[Description]  NVARCHAR(200),

	[ActivityType] NVARCHAR(50) NOT NULL,
	[ClientType] NVARCHAR(50) NOT NULL,
	[ClientName] NVARCHAR(50) NOT NULL,
	[ClientCode] NVARCHAR(50) NOT NULL DEFAULT '',

	[PlannedStartDate] DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
	[PlannedEndDate] DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
	[Comments] NVARCHAR(2048) NOT NULL,

	[Status] NVARCHAR(50) NOT NULL,
	[NotificationDate] DATETIME2 NOT NULL,
	[TimeStamp] DATETIME2 NOT NULL,

	[PhoneDbId] NVARCHAR(50) NOT NULL,
	[TaskId] BIGINT NOT NULL DEFAULT 0,
	[TaskAssignmentId] BIGINT NOT NULL DEFAULT 0,

	[IsProcessed] BIT NOT NULL DEFAULT 0,  
	[DateCreated] DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
	[DateUpdated] DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
	[ProjectId] BIGINT NOT NULL DEFAULT 1
)
GO