CREATE TABLE [dbo].[SqliteDayPlanTarget](
	[Id] BIGINT NOT NULL PRIMARY KEY IDENTITY,
	[BatchId] BIGINT NOT NULL REFERENCES dbo.SqliteActionBatch,
	[EmployeeId] BIGINT NOT NULL,
	[PlanDate]  DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
	[TargetSales] DECIMAL(19, 2) NOT NULL,
	[TargetCollection] DECIMAL(19, 2) NOT NULL,
	[TargetVigoreSales] DECIMAL(19, 2) NOT NULL DEFAULT 0,
	[TargetDealerAppointment] INT NOT NULL,
	[PhoneDbId] NVARCHAR(50) NOT NULL,
	[IsProcessed] BIT NOT NULL DEFAULT 0,
	[DayPlanTargetId] BIGINT NOT NULL DEFAULT 0,
	[DateCreated] DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
	[DateUpdated] DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
	[TargetDemoActivity] INT NOT NULL DEFAULT 0
)
GO