CREATE TABLE [dbo].[SqlitePayment]
(
	[Id] BIGINT NOT NULL PRIMARY KEY IDENTITY,
	[BatchId] BIGINT NOT NULL REFERENCES dbo.SqliteActionBatch,
	[EmployeeId] BIGINT NOT NULL,

	[PhoneDbId] NVARCHAR(50) NOT NULL DEFAULT '',
	[CustomerCode] NVARCHAR(50) NOT NULL,
	[PaymentType] NVARCHAR(10) NOT NULL, -- Cash/Cheque
	[PaymentDate] DATETIME2 NOT NULL,
	[TotalAmount] DECIMAL(19,2) NOT NULL,
	[Comment] NVARCHAR(2048),

	[ImageCount] INT NOT NULL DEFAULT 0,

	[PhoneActivityId] NVARCHAR(50) NOT NULL DEFAULT '',

	[IsProcessed] BIT NOT NULL DEFAULT 0,  -- non-unique indexed
	[PaymentId] BIGINT NOT NULL DEFAULT 0,
	[DateCreated] DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
	[DateUpdated] DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
)
