CREATE TABLE [dbo].[SqliteBankDetail]
(
	[Id] BIGINT NOT NULL PRIMARY KEY IDENTITY,
	[BatchId] BIGINT NOT NULL REFERENCES dbo.SqliteActionBatch,
	[EmployeeId] BIGINT NOT NULL,

	[IsNewEntity] BIT NOT NULL,
	[EntityId] BIGINT NOT NULL,
	[EntityName] NVARCHAR(50) NOT NULL,

	[IsSelfAccount] BIT NOT NULL,
	[AccountHolderName] NVARCHAR(50) NOT NULL,
	[AccountHolderPAN] NVARCHAR(50) NOT NULL,
	[BankName] NVARCHAR(50) NOT NULL,
	[BankAccount] NVARCHAR(50) NOT NULL,
	[BankIFSC] NVARCHAR(50) NOT NULL,
	[BankBranch] NVARCHAR(50) NOT NULL,

	[BankDetailDate] DATETIME2 NOT NULL,
	[ImageCount] INT NOT NULL DEFAULT 0,

	[ActivityId] NVARCHAR(50) NOT NULL DEFAULT '',
	[PhoneDbId] NVARCHAR(50) NOT NULL, 
	[ParentReferenceId]  NVARCHAR(50) NOT NULL DEFAULT '',

	[IsProcessed] BIT NOT NULL DEFAULT 0,  
	[EntityBankDetailId] BIGINT NOT NULL DEFAULT 0,
	[DateCreated] DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
	[DateUpdated] DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
)
