CREATE TABLE [dbo].[SqliteSTR]
(
	[Id] BIGINT NOT NULL PRIMARY KEY IDENTITY,
	[BatchId] BIGINT NOT NULL REFERENCES dbo.SqliteActionBatch,
	[EmployeeId] BIGINT NOT NULL,

	[STRNumber] NVARCHAR(50) NOT NULL,
	[VehicleNumber] NVARCHAR(50) NOT NULL,
	[DriverName] NVARCHAR(50) NOT NULL,
	[DriverPhone] NVARCHAR(50) NOT NULL,
	[DWSCount] BIGINT NOT NULL,
	[BagCount] BIGINT NOT NULL,
	[GrossWeight] DECIMAL(19,2) NOT NULL,
	[NetWeight] DECIMAL(19,2) NOT NULL,
	[StartOdometer] BIGINT NOT NULL,
	[EndOdometer] BIGINT NOT NULL,
	[STRDate] DATETIME2 NOT NULL,
	[IsNew] BIT NOT NULL,
	[IsTransferred] BIT NOT NULL,
	[TransfereeName] NVARCHAR(50) NOT NULL,
	[TransfereePhone] NVARCHAR(50) NOT NULL,

	[ImageCount] INT NOT NULL DEFAULT 0,
	[TimeStamp] DATETIME2 NOT NULL,
	[ActivityId] NVARCHAR(50) NOT NULL DEFAULT '',
	[TimeStamp2] DATETIME2 NOT NULL,
	[ActivityId2] NVARCHAR(50) NOT NULL DEFAULT '',
	[PhoneDbId] NVARCHAR(50) NOT NULL, 

	[IsProcessed] BIT NOT NULL DEFAULT 0,  
	[STRId] BIGINT NOT NULL DEFAULT 0,
	[DateCreated] DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
	[DateUpdated] DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
)
