CREATE TABLE [dbo].[Order]
(
	[Id] BIGINT NOT NULL PRIMARY KEY Identity,
	[EmployeeId] BIGINT NOT NULL REFERENCES TenantEmployee,
	[DayId] BIGINT NOT NULL REFERENCES dbo.[Day],
	[CustomerCode] NVARCHAR(50) NOT NULL,
	[OrderType] NVARCHAR(10) NOT NULL, -- 'New' / 'Return'
	[OrderDate] DATETIME2 NOT NULL,
	
	[ItemCount] BIGINT NOT NULL DEFAULT 0,
	[ImageCount] INT NOT NULL DEFAULT 0,

	[TotalAmount] DECIMAL(19,2) NOT NULL,
	[TotalGST] DECIMAL(19,2) NOT NULL DEFAULT 0,
	[NetAmount] DECIMAL(19,2) NOT NULL DEFAULT 0,

	[DiscountType] NVARCHAR(50) NOT NULL DEFAULT 'Amount',
	[DiscountPercentage] DECIMAL(5,2) NOT NULL DEFAULT 0,
	
	[RevisedDiscountPercentage] DECIMAL(5,2) NOT NULL DEFAULT 0,
	[RevisedTotalAmount] DECIMAL(19,2) DEFAULT 0 NOT NULL,
	[RevisedTotalGST] DECIMAL(19,2) NOT NULL DEFAULT 0,
	[RevisedNetAmount] DECIMAL(19,2) NOT NULL DEFAULT 0,

	-- approval fields
	[IsApproved] BIT NOT NULL DEFAULT 0,
	[ApproveDate] DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
	[ApproveRef] NVARCHAR(255),
	[ApproveNotes] NVARCHAR(2048),
	[ApproveAmount] DECIMAL(19,2) NOT NULL DEFAULT 0,
	[ApprovedBy] NVARCHAR(50) NOT NULL DEFAULT '',

	[IsCustomerSMSSent] BIT NOT NULL DEFAULT 0,
	[IsAgentSMSSent] BIT NOT NULL DEFAULT 0,

	[LockTimestamp] DATETIME2 NULL,
	[DateCreated] DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
	[DateUpdated] DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
	[SqliteOrderId] BIGINT NOT NULL,  -- used while processing orders from sqliteOrder table
	[IsExported] BIT NOT NULL DEFAULT 0,
	[ExportedDate] DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
)
