CREATE TABLE [dbo].[GstRate]
(
	[Id] BIGINT NOT NULL PRIMARY KEY IDENTITY,
	[GstCode] NVARCHAR(20) NOT NULL,
	[GstRate] DECIMAL(19,2) NOT NULL DEFAULT 0,
	[EffectiveStartDate] DATE NOT NULL,
	[EffectiveEndDate] DATE NOT NULL,

	[DateCreated] DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
	[DateUpdated] DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
	[CreatedBy] NVARCHAR(50) NOT NULL DEFAULT '',
	[UpdatedBy] NVARCHAR(50) NOT NULL DEFAULT '',
	[IsActive] Bit NOT NULL Default 1
)
