//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestConApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpenseItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ExpenseItem()
        {
            this.ExpenseItemImages = new HashSet<ExpenseItemImage>();
            this.ExpenseItemDetails = new HashSet<ExpenseItemDetail>();
        }
    
        public int Id { get; set; }
        public int ExpenseId { get; set; }
        public Nullable<int> CommentId { get; set; }
        public int SequenceNumber { get; set; }
        public string ExpenseTypeCode { get; set; }
        public decimal Amount { get; set; }
    
        public virtual Comment Comment { get; set; }
        public virtual Expense Expense { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExpenseItemImage> ExpenseItemImages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExpenseItemDetail> ExpenseItemDetails { get; set; }
    }
}
