//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestConApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderItem
    {
        public int Id { get; set; }
        public int OrderId { get; set; }
        public Nullable<int> CommentId { get; set; }
        public int SerialNumber { get; set; }
        public string ProductCode { get; set; }
        public int UnitQuantity { get; set; }
        public decimal UnitPrice { get; set; }
    
        public virtual Comment Comment { get; set; }
        public virtual Order Order { get; set; }
    }
}
