//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestConApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransportType
    {
        public int Id { get; set; }
        public int DisplaySequence { get; set; }
        public string TransportTypeCode { get; set; }
        public string TransportTypeText { get; set; }
        public decimal ReimbursementRatePerUnit { get; set; }
    }
}
