CREATE TABLE [dbo].[ProductPrice]
(
	[Id] INT NOT NULL PRIMARY KEY Identity,
	[ProductId] INT NOT NULL REFERENCES Product,
	[AreaCode] NVARCHAR(10),
	[Stock] BIGINT NOT NULL DEFAULT 0,
	[MRP] DECIMAL(19,2) NOT NULL DEFAULT 0,
	[DISTPrice] DECIMAL(19,2) NOT NULL,
	[PDISTPrice] DECIMAL(19,2) NOT NULL,
	[DEALERPrice] DECIMAL(19,2) NOT NULL,
)
