CREATE TABLE [dbo].[Project]
(
	[Id] BIGINT NOT NULL PRIMARY KEY IDENTITY,
	[Name] NVARCHAR(50) NOT NULL,
	[Description]  NVARCHAR(200),

	[PlannedStartDate] DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
	[PlannedEndDate] DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
	[ActualStartDate] DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
	[ActualEndDate] DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
	[ProjectCategory] NVARCHAR(50) NOT NULL,

	[Status] NVARCHAR(50) NOT NULL DEFAULT 'Open',
	[CyclicCount] INT NOT NULL DEFAULT 0,
	[IsActive] BIT NOT NULL DEFAULT 0,

	[DateCreated] DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
	[DateUpdated] DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
	[CreatedBy] NVARCHAR(50) NOT NULL,
	[UpdatedBy] NVARCHAR(50) NOT NULL
)
GO