CREATE TABLE [dbo].[ProjectAudit]
(
	[Id] BIGINT NOT NULL PRIMARY KEY IDENTITY,
	[XRefProjectId] BIGINT NOT NULL,
	[Name] NVARCHAR(50) NOT NULL,
	[Description]  NVARCHAR(200),

	[PlannedStartDate] DATETIME2 NOT NULL,
	[PlannedEndDate] DATETIME2 NOT NULL,
	[ActualStartDate] DATETIME2 NOT NULL,
	[ActualEndDate] DATETIME2 NOT NULL,
	[ProjectCategory] NVARCHAR(50) NOT NULL,

	[Status] NVARCHAR(50) NOT NULL,
	[IsActive] BIT NOT NULL DEFAULT 0,

	[DateCreated] DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
	[CreatedBy] NVARCHAR(50) NOT NULL
)
GO