CREATE TABLE [dbo].[TaskAssignment]
(
	[Id] INT NOT NULL PRIMARY KEY Identity,
	[XRefTaskId] BIGINT NOT NULL REFERENCES dbo.Task([Id]),
	[EmployeeId] BIGINT NOT NULL References dbo.TenantEmployee(Id),
	
	[StartDate] DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
	[EndDate] DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
	[IsAssigned] BIT NOT NULL DEFAULT 1,
	[IsSelfAssigned] BIT NOT NULL DEFAULT 0,
	[Comments] NVARCHAR(2048) NOT NULL,
	[DateCreated] DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
	[DateUpdated] DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
	[CreatedBy] NVARCHAR(50) NOT NULL DEFAULT '',
	[UpdatedBy] NVARCHAR(50) NOT NULL DEFAULT ''
)
GO